from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cc') + Glob('internal/*.cc')
tflm_pkg = ""
#riscv64-unknown-elf-gcc -E -dM main.c > a.txt
CXXFLAGS = " -DTF_LITE_USE_GLOBAL_CMATH_FUNCTIONS -DTF_LITE_USE_GLOBAL_MIN -DTF_LITE_USE_GLOBAL_MAX -DTF_LITE_STATIC_MEMORY "
CFLAGS = " -DTF_LITE_USE_GLOBAL_CMATH_FUNCTIONS -DTF_LITE_USE_GLOBAL_MIN -DTF_LITE_USE_GLOBAL_MAX -DTF_LITE_STATIC_MEMORY "

#.
root =  str(Dir('#'))
packages = os.path.join(root, 'packages')
file_list = os.listdir(packages)
for f in file_list:
    if(f.split('-')[0] == 'TensorflowLiteMicro'):
        tflm_pkg = os.path.join(packages, f)
        break
#./third_party/flatbuffer/include
flatbuffer = os.path.join(tflm_pkg, "third_party/flatbuffers/include")
#./third_party/gemmlowp
gemmlowp = os.path.join(tflm_pkg, "third_party/gemmlowp")
#./third_party/kissfft
kissfft = os.path.join(tflm_pkg, "third_party/kissfft")
#./third_party/ruy
ruy = os.path.join(tflm_pkg, "third_party/ruy")


CPPPATH = [tflm_pkg, flatbuffer, gemmlowp, kissfft, ruy]

group = DefineGroup('lite/kernels', src, depend = [''], CPPPATH = CPPPATH, CXXFLAGS = CXXFLAGS, CFLAGS=CFLAGS)

Return('group')
